---
title: "Untitled"
output: html_document
date: "2025-03-28"
---

```{r}
# Load TCGA PDAC data
data_meth = readRDS("../../datashare/TCGA_PAAD/study_TCGA-PAAD_meth.rds")
data_trans = readRDS("../../datashare/TCGA_PAAD/study_TCGA-PAAD_trscr.rds")
meta = read.csv2("../../datashare/TCGA_PAAD/PublishedSampleTable.csv",
                 header = TRUE)
raw_exp = read.delim("../../datashare/TCGA_PAAD/clinical.project-tcga-paad.2024-07-30/exposure.tsv")


tcga_data_deconv = readRDS("results/01_tcga_data_expo_deconv.rds")
X_deconv = tcga_data_deconv$X_deconv$Consensus
immune_cells = c("Macrophages","B cells", "T cells", "NK","DCs")
X_immune = X_deconv[rownames(X_deconv) %in% immune_cells,]


exposure = as.data.frame(raw_exp)

# smoking exposure
smoking = raw_exp$cigarettes_per_day
smoking = as.numeric(smoking)
smoking[is.na(smoking)] = 0
smoking_bin = smoking
smoking_bin[smoking>0] = 1

smoking_habits = data.frame(exposure$case_submitter_id, smoking_bin, exposure$cigarettes_per_day, exposure$pack_years_smoked, exposure$smoking_frequency, exposure$time_between_waking_and_first_smoke, exposure$tobacco_smoking_onset_year, exposure$tobacco_smoking_quit_year, exposure$tobacco_smoking_status, exposure$type_of_smoke_exposure, exposure$type_of_tobacco_used, exposure$use_per_day, exposure$years_smoked, exposure$tobacco_use_per_day)

write.csv(smoking_habits, "results/01_tcga_smoking_habits_variables.csv")


idx_to_keep = meta$Tumor.Sample.ID[which(meta$Tumor.Sample.ID %in% colnames(data_trans$data))]
dat_meth = data_meth$data[, idx_to_keep]
dat_trans = data_trans$data[, idx_to_keep]
meta = meta[meta$Tumor.Sample.ID %in% idx_to_keep,]
dim(dat_meth)
dim(dat_trans)

rownames(raw_exp) = paste0(raw_exp$case_submitter_id, "-01A")
raw_exp = raw_exp[idx_to_keep,]

# n=149

# remove NAs from dat_meth
idx_na_rows = apply(dat_meth, 1, function(x)
  any(is.na(x)))
dat_meth = dat_meth[!idx_na_rows,]
dim(dat_meth)

# filter out sex chromosomes
probes_chr = intersect(rownames(data_meth$platform)[!(data_meth$platform[,1] %in% c("chrX", "chrY", "*"))],
                   rownames(dat_meth))
probes_chr_CHR = data_meth$platform[probes_chr,]$Chromosome
probes_chr_BP = data_meth$platform[probes_chr,]$Start
probes_chr_GeneSymbol = data_meth$platform[probes_chr,]$Gene_Symbol
dat_meth = dat_meth[probes_chr,]

# remove rows summing to 0 - USELESS
#idx_zero = (rowSums(dat_meth) == 0)
#dat_meth = dat_meth[!idx_zero,]
#dim(dat_meth)

# keep only samples w/ follow up (n=145)
dat_trans = dat_trans[, !is.na(meta$Follow.up.days) & !is.na(meta$Censored.1.yes.0.no)]
dat_meth = dat_meth[, colnames(dat_trans)]
rownames(meta) = meta$Tumor.Sample.ID
meta = meta[colnames(dat_trans), ]
raw_exp = raw_exp[colnames(dat_trans), ]

rm(idx_na_rows,idx_to_keep,probes_chr)

gc()

```


```{r define_variables}
# M matrix
M = t(dat_meth)
dim(M)
# survival data
time = meta$Follow.up.days
cens = meta$Censored.1.yes.0.no

# smoking exposure
smoking = raw_exp$cigarettes_per_day
smoking = as.numeric(smoking)
smoking[is.na(smoking)] = 0
smoking_bin = smoking
smoking_bin[smoking>0] = 1

# alcohol exposure
alcohol = raw_exp$alcohol_history
alcohol[alcohol=="Yes"] = 1
alcohol[alcohol=="No"] = 0
alcohol[alcohol=="Not Reported"] = NA
alcohol = as.numeric(alcohol)

# covariables
age = meta$Age.at.initial.pathologic.diagnosis
sex = meta$Gender
sex[which(sex == "male")] = 1
sex[which(sex == "female")] = 2
gender = as.numeric(sex)
grade = meta$Grade
grade = as.numeric(sapply(grade, function(x) strsplit(x," ", fixed=T)[[1]][2]))
```




```{r ACP 1}
covar = cbind(sex, age, grade)
covar_df = as.data.frame(covar)

# Créer la matrice des résidus vide
res_mat <- matrix(NA, nrow = nrow(M), ncol = ncol(M))
colnames(res_mat) <- colnames(M)
rownames(res_mat) <- rownames(M)
# Boucle sur chaque CpG
for (j in seq_len(ncol(M))) {
  y <- M[, j]
  mod <- lm(y ~ ., data = covar_df)  # ajustement sur toutes les covariables
  res_mat[, j] <- resid(mod)         # résidus du modèle
}




pca <- prcomp(res_mat, center = FALSE, scale. = FALSE)

pdf("figures/01_TCGA_scree_plot.pdf", width = 7, height = 5)

plot((pca$sdev^2/sum(pca$sdev^2))[1:10],
     type = "b",
     xlab = 'Principal Component',
     ylab = "Explained variance",
     main = "PCA on adjusted TCGA methylation matrix")

  # ton objet ggplot
dev.off()

```


```{r ACP 2}
covar = cbind(gender, age, grade, immune_cells)
covar_df = as.data.frame(covar)

# Créer la matrice des résidus vide
res_mat <- matrix(NA, nrow = nrow(M), ncol = ncol(M))
colnames(res_mat) <- colnames(M)
rownames(res_mat) <- rownames(M)
# Boucle sur chaque CpG
for (j in seq_len(ncol(M))) {
  y <- M[, j]
  mod <- lm(y ~ ., data = covar_df)  # ajustement sur toutes les covariables
  res_mat[, j] <- resid(mod)         # résidus du modèle
}

# On centre et réduit avant PCA
#res_mat_scaled <- scale(res_mat)
# PCA
pca <- prcomp(res_mat, center = FALSE, scale. = FALSE)

pdf("figures/01_TCGA_scree_plot_alter.pdf", width = 7, height = 5)

plot((pca$sdev^2/sum(pca$sdev^2))[1:10],
     type = "b",
     xlab = 'Principal Component',
     ylab = "Explained variance",
     main = "PCA on adjusted TCGA methylation matrix")

  # ton objet ggplot
dev.off()

```

