---
title: "step2 mediation"
output: html_document
date: "2025-07-11"
---


```{r init}
library(survival)
library(ggplot2)
library(epimedtools)
source("surv_parametric_alternative.R")
source("helper_functions.R")

source("surv_aalen_alternative.R")
set.seed(123)
```



# TCGA data V2 K8 corrected

```{r load4}

med_tobacco_dnam = readRDS("results/02_tcga_med_tobacco_dnam_V2_K8_corrected.rds")
data_tcga = readRDS("results/01_tcga_data_expo_deconv.rds")

```

```{r step2}
library(hdmax2)
med_tobacco_dnam$hdmax2_step1_param$max2_pvalues

q_values = hdmax2::hdmax2_qvalue(med_tobacco_dnam$hdmax2_step1_param$max2_pvalues)

candidate_mediator_005 <- q_values$qv[q_values$qv<= 0.05]
candidate_mediator_005

m_005 = data_tcga$M[, names(candidate_mediator_005)]

hdmax2_step2_005 = estimate_effect_surv_param(object = med_tobacco_dnam$hdmax2_step1_param, m = m_005)

acme = hdmax2_step2_005$effects$univariate$ACME
res_005 = list(all_step2_res = hdmax2_step2_005,
              step2_res_4 = acme,
              meth_mat = m_005)
saveRDS(res_005, "results/03_tcga_top50_tobacco_CPG_fdr0_05_V2_K8_corrected.rds")
```


```{r}
candidate_mediator_01 <- q_values$qv[q_values$qv<= 0.1]
candidate_mediator_01

m_01 = data_tcga$M[, names(candidate_mediator_01)]

hdmax2_step2_01 = estimate_effect_surv_param(object = med_tobacco_dnam$hdmax2_step1_param, m = m_01)

acme = hdmax2_step2_01$effects$univariate$ACME
res_01 = list(all_step2_res = hdmax2_step2_01,
              step2_res_6 = acme,
              meth_mat = m_01)
saveRDS(res_01, "results/03_tcga_top50_tobacco_CPG_fdr0_1_V2_K8_corrected.rds")
```

```{r}
set.seed(123)
######################
#AMR research
######################
pf_meth = data.frame("Chromosome"=data_tcga$probes_info$CHR,
                     "Start"=data_tcga$probes_info$BP,
                     "End"=data_tcga$probes_info$End,
                     "Gene_Symbol"=data_tcga$probes_info$Gene_Symbol)
rownames(pf_meth) = colnames(data_tcga$M)

# hist(med_tobacco_dnam$hdmax2_step1_param$max2_pvalues)
# hist(qnorm(med_tobacco_dnam$hdmax2_step1_param$max2_pvalues))

# AMR resaerch
res.amr_search = AMR_search(chr = pf_meth$Chromosome,
                                    start = pf_meth$Start,
                                    end = pf_meth$End,
                                    pval = med_tobacco_dnam$hdmax2_step1_param$max2_pvalues,
                                    cpg = rownames(pf_meth),
                                    seed = 0.1, 
                                    nCores = 1)

res.amr_build = AMR_build(res.amr_search,
                                  methylation = data_tcga$M, 
                                  nb_cpg = 2)

# total AMR
m = as.matrix(res.amr_build$AMR_mean)

saveRDS(m, "results/03_tcga_mean_meth_AMR_fdr0_1_V2_K8_corrected.rds")
saveRDS(res.amr_build, "results/03_tcga_tobacco_AMR_fdr0_1_V2_K8_corrected.rds")

# top 50 AMR (most significative according to combp pval)
res = res.amr_build$res
mean_meth = res.amr_build$AMR_mean
cpg_related = res.amr_build$CpG_for_each_AMR
order_AMR = res[order(res.amr_build$res$p),]
top_50_AMR = order_AMR[1:50,]
mean_meth_50 = mean_meth[,top_50_AMR$AMR]
cpg_related_50 = cpg_related[top_50_AMR$AMR]
rownames(mean_meth_50) = rownames(data_tcga$M)

# # save amr built results and methylation matrix for top 50
# res_50 = list(cpg_related_50 = cpg_related_50, top_50_AMR_res = top_50_AMR, mean_meth_50 = mean_meth_50)
# saveRDS(res_50 , "results/03_tcga_top50_tobacco_AMR_fdr0_1_V2_K5.rds")

rownames(m) = rownames(data_tcga$M)
mean_meth_50 = as.matrix(mean_meth_50)

## selected mediators effects estimation
hdmax2_step2 = estimate_effect_surv_param(object = med_tobacco_dnam$hdmax2_step1_param, m = mean_meth_50)
acme = hdmax2_step2$effects$univariate$ACME
significative_AMR_acme = acme[which(acme$pval<=0.05),]
mean_meth_significative = m[, significative_AMR_acme$feat]
saveRDS(mean_meth_significative, "results/03_tcga_significative_from_top50_mean_meth_AMR_fdr0_1_V2_K8_corrected.rds")

AMR_info = res.amr_build$res
CpG_related_info = res.amr_build$CpG_for_each_AMR
CpG_related_info_significative = res.amr_build$CpG_for_each_AMR[AMR_info$AMR %in% significative_AMR_acme$feat]
significative_AMR_info = AMR_info[AMR_info$AMR %in% significative_AMR_acme$feat,]

res_50 = list(all_step2_res = hdmax2_step2,
              step2_res_50 = acme,
              AMR_info_50  = AMR_info[AMR_info$AMR %in% top_50_AMR$AMR,],
              cpg_related_50 = cpg_related_50,
              mean_meth_mat = mean_meth_50)
saveRDS(res_50, "results/03_tcga_top50_tobacco_AMR_fdr0_1_V2_K8_corrected.rds")

res = list(
  step2_res = significative_AMR_acme,
  AMR_info = significative_AMR_info,
  CpG_related_info = CpG_related_info_significative
)

saveRDS(res, "results/03_tcga_significative_from_top50_tobacco_AMR_fdr0_1_V2_K8_corrected.rds")

# for causal direction analyses (Nelle)
write.csv(mean_meth_50, "results/03_tcga_AMR_mean_meth_top50_fdr0_1_V2_K8_corrected.csv")

write.csv(mean_meth_significative, "results/03_tcga_AMR_mean_meth_significative_fdr0_1_V2_K8_corrected.csv")

```


