---
title: "Correlation between AMR and Immune cells"
output: html_document
date: "2025-03-22"
---


# K=8 corrected


```{r correlation AMR immune V2 K8}
library(reshape2)

deconv = readRDS("results/01_tcga_data_expo_deconv.rds")
mean_meth_AMR = readRDS("results/03_tcga_top50_tobacco_AMR_fdr0_05_V2_K8_corrected.rds")
mean_meth_AMR = mean_meth_AMR$mean_meth_mat
X_deconv = deconv$X_deconv$Consensus
immune_cells = c("Macrophages","B cells", "T cells", "NK","DCs")
X_immune = X_deconv[rownames(X_deconv) %in% immune_cells,]
immune_cons = t(X_immune)

dim(mean_meth_AMR)
dim(immune_cons)

cor_matrix <- cor(mean_meth_AMR, immune_cons, use = "pairwise.complete.obs", method = "pearson")

# Make a df
cor_df <- as.data.frame(as.table(cor_matrix))
colnames(cor_df) <- c("DNAm", "Immune", "Correlation")

get_pval <- function(x, y) {
  test <- cor.test(x, y, use = "pairwise.complete.obs", method = "pearson")
  return(test$p.value)
}

get_corr <- function(x, y) {
  test <- cor.test(x, y, use = "pairwise.complete.obs", method = "pearson")
  return(test$estimate)
}

pval_matrix <- matrix(NA, ncol = ncol(immune_cons), nrow = ncol(mean_meth_AMR),
                      dimnames = list(colnames(mean_meth_AMR),
                                      colnames(immune_cons)))
for (i in 1:ncol(mean_meth_AMR)) {
  for (j in 1:ncol(immune_cons)) {
    pval_matrix[i, j] <- get_pval(mean_meth_AMR[, i], immune_cons[, j])
  }
}

corr_matrix <- matrix(NA, ncol = ncol(immune_cons), nrow = ncol(mean_meth_AMR),
                      dimnames = list(colnames(mean_meth_AMR),
                                      colnames(immune_cons)))
for (i in 1:ncol(mean_meth_AMR)) {
  for (j in 1:ncol(immune_cons)) {
    corr_matrix[i, j] <- get_corr(mean_meth_AMR[, i], immune_cons[, j])
  }
}

# Long format
cor_df <- melt(cor_df, varnames = c("DNAm", "Immune"), value.name = "Correlation")
pval_df <- melt(pval_matrix, varnames = c("DNAm", "Immune"), value.name = "P_value")
corr_df <- melt(corr_matrix, varnames = c("DNAm", "Immune"), value.name = "corr")
pval_df$variable = rep("P_value", dim(pval_df)[1] )

plot_df = data.frame(AMR = cor_df$DNAm,
                     correlation = cor_df$Correlation,
                     pvalue = pval_df$P_value,
                     cell_type = pval_df$Immune,
                     corr = corr_df$corr)
df_to_save = data.frame(AMR = cor_df$DNAm,
                        pvalue = pval_df$P_value,
                        cell_type = pval_df$Immune,
                        corr = corr_df$corr)
saveRDS(df_to_save, "results/04_tcga_AMR_imm_corr_fdr0_05_V2_K8_corrected.rds")

res = list(immune_cons = immune_cons, mean_meth_AMR = mean_meth_AMR)
saveRDS(res, "results/04_tcga_imm_AMR_matrix_fdr0_05_V2_K8_corrected.rds")
```

```{r latent factor immune cells correlation V2_K8}

med_tobacco_dnam_CpG = readRDS("results/02_tcga_med_tobacco_dnam_V2_K8_corrected.rds")
latent_factor = med_tobacco_dnam_CpG$hdmax2_step1_param$AS_1$U

# deconv = readRDS("results/01_tcga_data_expo_deconv.rds")
# immune_cons = deconv$X_deconv$Consensus
# immune_cons = immune_cons[-1, ]
# immune_cons = t(immune_cons)

cor_matrix_LF <- cor(latent_factor, immune_cons, use = "pairwise.complete.obs", method = "pearson")
# Make a df
cor_df_LF <- as.data.frame(as.table(cor_matrix_LF))
colnames(cor_df_LF) <- c("LF", "Immune", "Correlation")

pval_matrix_LF <- matrix(
  NA,
  ncol = ncol(immune_cons),
  nrow = ncol(latent_factor),
  dimnames = list(colnames(latent_factor), colnames(immune_cons))
)

for (i in 1:ncol(latent_factor)) {
  for (j in 1:ncol(immune_cons)) {
    pval_matrix_LF[i, j] <- get_pval(latent_factor[, i], immune_cons[, j])
  }
}

corr_matrix_LF <- matrix(
  NA,
  ncol = ncol(immune_cons),
  nrow = ncol(latent_factor),
  dimnames = list(colnames(latent_factor), colnames(immune_cons))
)
for (i in 1:ncol(latent_factor)) {
  for (j in 1:ncol(immune_cons)) {
    corr_matrix_LF[i, j] <- get_corr(latent_factor[, i], immune_cons[, j])
  }
}

cor_df_LF <- melt(cor_df_LF,
                  varnames = c("LF", "Immune"),
                  value.name = "Correlation")
pval_df_LF <- melt(pval_matrix_LF,
                   varnames = c("LF", "Immune"),
                   value.name = "P_value")
corr_df_LF <- melt(corr_matrix_LF,
                   varnames = c("LF", "Immune"),
                   value.name = "corr")
pval_df_LF$variable = rep("P_value", dim(pval_df_LF)[1])

plot_df_LF = data.frame(
  latent_factor = cor_df_LF$LF,
  correlation = cor_df_LF$Correlation,
  pvalue = pval_df_LF$P_value,
  cell_type = pval_df_LF$Immune,
  corr = corr_df_LF$corr
)
df_to_save_latent_factor = data.frame(
  latent_factor = cor_df_LF$LF,
  pvalue = pval_df_LF$P_value,
  cell_type = pval_df_LF$Immune,
  corr = corr_df_LF$corr
)
saveRDS(df_to_save_latent_factor, "results/04_tcga_LF_imm_corr_fdr0_05_V2_K8_corrected.rds")

res = list(immune_cons = immune_cons, latent_factor = latent_factor)

saveRDS(res, "results/04_tcga_imm_LF_matrix_fdr0_05_V2_K8_corrected.rds")

```

```{r}
library(dplyr)

# Chargement des données
med_tobacco_dnam_CpG = readRDS("results/02_tcga_med_tobacco_dnam_V2_K8_corrected.rds")
latent_factor = med_tobacco_dnam_CpG$hdmax2_step1_param$AS_1$U

mean_meth_AMR = readRDS("results/03_tcga_top50_tobacco_AMR_fdr0_05_V2_K8_corrected.rds")
mean_meth_AMR = mean_meth_AMR$mean_meth_mat

# Corrélation Pearson
cor_AMR_LF_matrix <- cor(mean_meth_AMR, latent_factor, use = "pairwise.complete.obs", method = "pearson")

# Conversion de la matrice en data.frame long
cor_df_LF_AMR <- as.data.frame(as.table(cor_AMR_LF_matrix))
colnames(cor_df_LF_AMR) <- c("AMR", "LF", "Correlation")

# Matrices pour p-values et corrélations
pval_matrix_LF_AMR <- matrix(NA,
  ncol = ncol(mean_meth_AMR),
  nrow = ncol(latent_factor),
  dimnames = list(colnames(latent_factor), colnames(mean_meth_AMR))
)

corr_matrix_LF_AMR <- matrix(NA,
  ncol = ncol(mean_meth_AMR),
  nrow = ncol(latent_factor),
  dimnames = list(colnames(latent_factor), colnames(mean_meth_AMR))
)

# Calcul des p-values et corrélations
for (i in 1:ncol(latent_factor)) {
  for (j in 1:ncol(mean_meth_AMR)) {
    pval_matrix_LF_AMR[i, j] <- get_pval(latent_factor[, i], mean_meth_AMR[, j])
    corr_matrix_LF_AMR[i, j] <- get_corr(latent_factor[, i], mean_meth_AMR[, j])
  }
}

# Transformation des matrices en data.frame long
pval_df_LF_AMR <- as.data.frame(as.table(pval_matrix_LF_AMR))
colnames(pval_df_LF_AMR) <- c("LF", "AMR", "P_value")

corr_df_LF_AMR <- as.data.frame(as.table(corr_matrix_LF_AMR))
colnames(corr_df_LF_AMR) <- c("LF", "AMR", "corr")

# Jointure finale
df_to_save_latent_factor <- cor_df_LF_AMR %>%
  left_join(pval_df_LF_AMR, by = c("LF", "AMR")) %>%
  left_join(corr_df_LF_AMR, by = c("LF", "AMR"))

# Sauvegarde
saveRDS(df_to_save_latent_factor, "results/04_tcga_LF_AMR_corr_fdr0_05_V2_K8_corrected.rds")

res = list(mean_meth_AMR = mean_meth_AMR, latent_factor = latent_factor)
saveRDS(res, "results/04_tcga_AMR_LF_matrix_fdr0_05_V2_K8_corrected.rds")

```


```{r}

med_tobacco_dnam_CpG = readRDS("results/02_tcga_med_tobacco_dnam_V2_K8_corrected.rds")
covars = med_tobacco_dnam_CpG$hdmax2_step1_param$input$covar
colnames(covars) = c("grade", "age", "genre")
colnames(latent_factor) = c("LF1","LF2","LF3","LF4","LF5","LF6","LF7","LF8")
all_covars = cbind(latent_factor, covars)
cor_COV_COV_matrix <- cor(all_covars, all_covars, use = "pairwise.complete.obs", method = "pearson")


cor_df_COV_COV <- as.data.frame(as.table(cor_COV_COV_matrix))
colnames(cor_df_COV_COV) <- c("COV1", "COV2", "Correlation")

# Matrices pour p-values et corrélations
pval_matrix_COV_COV <- matrix(NA,
  ncol = ncol(all_covars),
  nrow = ncol(all_covars),
  dimnames = list(colnames(all_covars), colnames(all_covars))
)

corr_matrix_COV_COV <- matrix(NA,
  ncol = ncol(all_covars),
  nrow = ncol(all_covars),
  dimnames = list(colnames(all_covars), colnames(all_covars))
)

# Calcul des p-values et corrélations
for (i in 1:ncol(all_covars)) {
  for (j in 1:ncol(all_covars)) {
    pval_matrix_COV_COV[i, j] <- get_pval(all_covars[, i], all_covars[, j])
    corr_matrix_COV_COV[i, j] <- get_corr(all_covars[, i], all_covars[, j])
  }
}

# Transformation des matrices en data.frame long
pval_df_COV_COV <- as.data.frame(as.table(pval_matrix_COV_COV))
colnames(pval_df_COV_COV) <- c("COV1", "COV2", "P_value")

corr_df_COV_COV <- as.data.frame(as.table(corr_matrix_COV_COV))
colnames(corr_df_COV_COV) <- c("COV1", "COV2", "corr")

# Jointure finale
df_to_save_all_covars <- cor_df_COV_COV %>%
  left_join(pval_df_COV_COV, by = c("COV1", "COV2")) %>%
  left_join(corr_df_COV_COV, by = c("COV1", "COV2"))

# Sauvegarde
saveRDS(df_to_save_all_covars, "results/04_tcga_COV_COV_corr_fdr0_05_V2_K8_corrected.rds")

res = list(all_covars = all_covars, all_covars = all_covars)
saveRDS(res, "results/04_tcga_COV_COV_matrix_fdr0_05_V2_K8_corrected.rds")



```


```{r}

med_tobacco_dnam_CpG = readRDS("results/02_tcga_med_tobacco_dnam_V2_K8_corrected.rds")
covars = med_tobacco_dnam_CpG$hdmax2_step1_param$input$covar
colnames(covars) = c("grade", "age", "genre")
colnames(latent_factor) = c("LF1","LF2","LF3","LF4","LF5","LF6","LF7","LF8")
all_covars = cbind(latent_factor, covars)

cor_AMR_COV_matrix <- cor(all_covars, mean_meth_AMR, use = "pairwise.complete.obs", method = "pearson")


cor_df_AMR_COV <- as.data.frame(as.table(cor_AMR_COV_matrix))
colnames(cor_df_AMR_COV) <- c( "COV", "AMR", "Correlation")

# Matrices pour p-values et corrélations
pval_matrix_AMR_COV <- matrix(NA,
  ncol = ncol(mean_meth_AMR),
  nrow = ncol(all_covars),
  dimnames = list(colnames(all_covars), colnames(mean_meth_AMR))
)

corr_matrix_AMR_COV <- matrix(NA,
  ncol = ncol(mean_meth_AMR),
  nrow = ncol(all_covars),
  dimnames = list(colnames(all_covars), colnames(mean_meth_AMR))
)

# Calcul des p-values et corrélations
for (i in 1:ncol(all_covars)) {
  for (j in 1:ncol(mean_meth_AMR)) {
    pval_matrix_AMR_COV[i, j] <- get_pval(all_covars[, i], mean_meth_AMR[, j])
    corr_matrix_AMR_COV[i, j] <- get_corr(all_covars[, i], mean_meth_AMR[, j])
  }
}

# Transformation des matrices en data.frame long
pval_df_AMR_COV <- as.data.frame(as.table(pval_matrix_AMR_COV))
colnames(pval_df_AMR_COV) <- c("COV", "AMR" , "P_value")

corr_df_AMR_COV <- as.data.frame(as.table(corr_matrix_AMR_COV))
colnames(corr_df_AMR_COV) <- c("COV", "AMR", "corr")

# Jointure finale
df_to_save_AMR_COV <- cor_df_AMR_COV %>%
  left_join(pval_df_AMR_COV, by = c("COV", "AMR")) %>%
  left_join(corr_df_AMR_COV, by = c("COV", "AMR"))

# Sauvegarde
saveRDS(df_to_save_AMR_COV, "results/04_tcga_AMR_COV_corr_fdr0_05_V2_K8_corrected.rds")

# res = list(all_covars = all_covars, all_covars = all_covars)
# saveRDS(res, "results/04_tcga_AMR_COV_matrix_fdr0_05_V2_K8_corrected.rds")
# 


```


```{r}


cor_AMR_AMR_matrix <- cor(mean_meth_AMR, mean_meth_AMR, use = "pairwise.complete.obs", method = "pearson")


cor_df_AMR_AMR <- as.data.frame(as.table(cor_AMR_AMR_matrix))
colnames(cor_df_AMR_AMR) <- c("AMR1", "AMR2", "Correlation")

# Matrices pour p-values et corrélations
pval_matrix_AMR_AMR <- matrix(NA,
  ncol = ncol(mean_meth_AMR),
  nrow = ncol(mean_meth_AMR),
  dimnames = list(colnames(mean_meth_AMR), colnames(mean_meth_AMR))
)

corr_matrix_AMR_AMR <- matrix(NA,
  ncol = ncol(mean_meth_AMR),
  nrow = ncol(mean_meth_AMR),
  dimnames = list(colnames(mean_meth_AMR), colnames(mean_meth_AMR))
)

# Calcul des p-values et corrélations
for (i in 1:ncol(mean_meth_AMR)) {
  for (j in 1:ncol(mean_meth_AMR)) {
    pval_matrix_AMR_AMR[i, j] <- get_pval(mean_meth_AMR[, i], mean_meth_AMR[, j])
    corr_matrix_AMR_AMR[i, j] <- get_corr(mean_meth_AMR[, i], mean_meth_AMR[, j])
  }
}

# Transformation des matrices en data.frame long
pval_df_AMR_AMR <- as.data.frame(as.table(pval_matrix_AMR_AMR))
colnames(pval_df_AMR_AMR) <- c("AMR1", "AMR2", "P_value")

corr_df_AMR_AMR <- as.data.frame(as.table(corr_matrix_AMR_AMR))
colnames(corr_df_AMR_AMR) <- c("AMR1", "AMR2", "corr")

# Jointure finale
df_to_save_mean_meth_AMR <- cor_df_AMR_AMR %>%
  left_join(pval_df_AMR_AMR, by = c("AMR1", "AMR2")) %>%
  left_join(corr_df_AMR_AMR, by = c("AMR1", "AMR2"))

# Sauvegarde
saveRDS(df_to_save_mean_meth_AMR, "results/04_tcga_AMR_AMR_corr_fdr0_05_V2_K8_corrected.rds")

res = list(mean_meth_AMR = mean_meth_AMR, mean_meth_AMR = mean_meth_AMR)
saveRDS(res, "results/04_tcga_AMR_AMR_matrix_fdr0_05_V2_K8_corrected.rds")



```



```{r}
cor_imm_imm_matrix <- cor(immune_cons, immune_cons, use = "pairwise.complete.obs", method = "pearson")

cor_df_imm_imm <- as.data.frame(as.table(cor_imm_imm_matrix))
colnames(cor_df_imm_imm) <- c("Immune1", "Immune2", "Correlation")

# Matrices pour p-values et corrélations
pval_matrix_imm_imm <- matrix(NA,
  ncol = ncol(immune_cons),
  nrow = ncol(immune_cons),
  dimnames = list(colnames(immune_cons), colnames(immune_cons))
)

corr_matrix_imm_imm <- matrix(NA,
  ncol = ncol(immune_cons),
  nrow = ncol(immune_cons),
  dimnames = list(colnames(immune_cons), colnames(immune_cons))
)

# Calcul des p-values et corrélations
for (i in 1:ncol(immune_cons)) {
  for (j in 1:ncol(immune_cons)) {
    pval_matrix_imm_imm[i, j] <- get_pval(immune_cons[, i], immune_cons[, j])
    corr_matrix_imm_imm[i, j] <- get_corr(immune_cons[, i], immune_cons[, j])
  }
}

# Transformation des matrices en data.frame long
pval_df_imm_imm <- as.data.frame(as.table(pval_matrix_imm_imm))
colnames(pval_df_imm_imm) <- c("Immune1", "Immune2", "P_value")

corr_df_imm_imm <- as.data.frame(as.table(corr_matrix_imm_imm))
colnames(corr_df_imm_imm) <- c("Immune1", "Immune2", "corr")

# Jointure finale
df_to_save_immune_cons <- cor_df_imm_imm %>%
  left_join(pval_df_imm_imm, by = c("Immune1", "Immune2")) %>%
  left_join(corr_df_imm_imm, by = c("Immune1", "Immune2"))

# Sauvegarde
saveRDS(df_to_save_immune_cons, "results/04_tcga_imm_imm_corr_fdr0_05_V2_K8_corrected.rds")

res = list(immune_cons = immune_cons, immune_cons = immune_cons)
saveRDS(res, "results/04_tcga_imm_imm_matrix_fdr0_05_V2_K8_corrected.rds")
```
